import React from 'react';
import { Lock, FileText, Cpu } from 'lucide-react';

export default function TrustSection() {
  return (
    <section className="section-padding" style={{ borderTop: '1px solid var(--border-translucent)', borderBottom: '1px solid var(--border-translucent)' }}>
      <div className="container">
        <div className="trust-grid">
          <div className="trust-item">
            <div className="trust-icon">
              <Lock size={22} />
            </div>
            <div>
              <h3 className="trust-title">Transient Data & Privacy First</h3>
              <p className="trust-text">
                Your financial numbers are processed securely in transient server memory. We never sell personally identifiable information (PII) or report your queries to credit bureaus.
              </p>
            </div>
          </div>

          <div className="trust-item">
            <div className="trust-icon">
              <FileText size={22} />
            </div>
            <div>
              <h3 className="trust-title">Independent Financial Estimates</h3>
              <p className="trust-text">
                Aegis Underwrite is an analytical decision platform, not a direct lender. Our estimates reflect standard BFSI FOIR guidelines (40–50%), but final approval rests with your individual banking institution.
              </p>
            </div>
          </div>

          <div className="trust-item">
            <div className="trust-icon">
              <Cpu size={22} />
            </div>
            <div>
              <h3 className="trust-title">Deterministic AI Reasoning</h3>
              <p className="trust-text">
                Our AI reasoning is generated by Anthropic Claude 3.5 Sonnet, primed strictly on verified mathematical outputs to eliminate hallucinations and deliver grounded financial guidance.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
